#ifndef LIBC_INCLUDE_EXTENSIONS_INTERNAL_INVOKE_HPP_
#define LIBC_INCLUDE_EXTENSIONS_INTERNAL_INVOKE_HPP_

#include <extensions/type_traits.hpp>

#endif  // LIBC_INCLUDE_EXTENSIONS_INTERNAL_INVOKE_HPP_
