#!/bin/bash

CONFIGURE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
CONFIGURE_SCRIPT_PATH="${CONFIGURE_DIR}/$(basename "$0")"
CONFIGURE_CMAKE_PATH="${CONFIGURE_DIR}/../../alkos/CMakeLists.txt"
CONFIGURE_TOOLCHAIN_DIR="${CONFIGURE_DIR}/../../alkos/toolchains"
CONFIGURE_FEATURE_FLAGS_PATH="${CONFIGURE_DIR}/feature_flags.conf"
CONFIGURE_FEATURE_FLAGS_DEFS_PATH="${CONFIGURE_DIR}/feature_flags_defs.yaml"
CONFIGURE_FEATURE_FLAGS_CXX_PATH="${CONFIGURE_DIR}/../../alkos/generated/include/autogen/feature_flags.h"

source "${CONFIGURE_DIR}/../utils/pretty_print.bash"
source "${CONFIGURE_DIR}/../utils/helpers.bash"

declare -A CONFIGURE_TOOLCHAINS=(
  ["x86_64"]="${CONFIGURE_TOOLCHAIN_DIR}/x86_64-toolchain.cmake"
)

declare -A CONFIGURE_FLAGS=(
  ["x86_64"]="${CONFIGURE_TOOLCHAIN_DIR}/x86_64-flags.cmake"
)

declare -A CONFIGURE_BUILD_TYPES_DESC=(
  ["debug"]="Build in debug. Capable of running on real hardware."
  ["release"]="Build in release. Capable of running on real hardware."
)

declare -A CONFIGURE_CMAKE_BUILD_TYPES=(
  ["debug"]="Debug"
  ["release"]="Release"
)

CONFIGURE_BUILD_DIR=""
CONFIGURE_TOOL_BINARIES_DIR=""
CONFIGURE_ARCH=""
CONFIGURE_BUILD_TYPE=""
CONFIGURE_VERBOSE=false

help() {
  echo "${CONFIGURE_SCRIPT_PATH} <arch> <build> [-b <BUILD_DIR>] [-t <TOOL_DIR>] [--verbose | -v]"
  echo "Where:"
  echo "<arch> - MANDATORY - architecture to build for. Supported are listed below."
  echo "<build> - MANDATORY - build type to configure. Supported are listed below."
  echo "-b <BUILD_DIR> - directory to store build files. Default is 'build' in repo parent dir."
  echo "-t <TOOL_DIR> - directory to store tool binaries. Default is 'tools' in repo parent dir."
  echo "--verbose | -v - flag to enable verbose output"

  echo ""
  echo "Supported architectures:"
  for arch in "${!CONFIGURE_TOOLCHAINS[@]}"; do
    echo "  ${arch}"
  done

  echo ""
  echo "Supported build types:"
  for build in "${!CONFIGURE_BUILD_TYPES_DESC[@]}"; do
    echo "  ${build} - ${CONFIGURE_BUILD_TYPES_DESC[${build}]}"
  done
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help)
        help
        exit 0
        ;;
      -b)
        CONFIGURE_BUILD_DIR="$2"
        shift 2
        ;;
      -t)
        CONFIGURE_TOOL_BINARIES_DIR="$2"
        shift 2
        ;;
      -v|--verbose)
        CONFIGURE_VERBOSE=true
        shift
        ;;
      -*)
        dump_error "Unknown argument: $1"
        exit 1
        ;;
      *)
        if [[ -z "$CONFIGURE_ARCH" ]]; then
          CONFIGURE_ARCH="$1"
        elif [[ -z "$CONFIGURE_BUILD_TYPE" ]]; then
          CONFIGURE_BUILD_TYPE="$1"
        else
          dump_error "Unknown argument: $1"
          exit 1
        fi
        shift
        ;;
    esac
  done
}

process_args() {
  if [[ -z "$CONFIGURE_ARCH" ]]; then
    dump_error "Architecture not specified. Use -h for help."
    exit 1
  fi

  if [[ -z "$CONFIGURE_BUILD_TYPE" ]]; then
    dump_error "Build type not specified. Use -h for help."
    exit 1
  fi

  if [[ -z "${CONFIGURE_TOOLCHAINS[$CONFIGURE_ARCH]}" ]]; then
    dump_error "Unsupported architecture: $CONFIGURE_ARCH. Use -h for help."
    exit 1
  fi

  if [[ -z "${CONFIGURE_BUILD_TYPES_DESC[$CONFIGURE_BUILD_TYPE]}" ]]; then
    dump_error "Unsupported build type: $CONFIGURE_BUILD_TYPE. Use -h for help."
    exit 1
  fi

  # Set default values if not provided
  [[ -z "$CONFIGURE_BUILD_DIR" ]] && CONFIGURE_BUILD_DIR="${CONFIGURE_DIR}/../../build"
  [[ -z "$CONFIGURE_TOOL_BINARIES_DIR" ]] && CONFIGURE_TOOL_BINARIES_DIR="${CONFIGURE_DIR}/../../tools"
}

generate_feature_flags_file() {
  echo "#!/bin/bash" > "${CONFIGURE_FEATURE_FLAGS_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
  echo "declare -A CONFIGURE_FEATURE_FLAGS" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
}

generate_cxx_feature_flag_files() {
  # Source the feature flags to load existing flags
  source "${CONFIGURE_FEATURE_FLAGS_PATH}"

  # Remove old header
  rm -f "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  touch "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  echo "// This file is generated by configure script. Do not edit manually." > "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "#ifndef GENERATED_INCLUDE_AUTOGEN_H_" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "#define GENERATED_INCLUDE_AUTOGEN_H_" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"


  # C code macros
  echo "// Macros for feature flags in C code" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  local flag_names
  mapfile -t flag_names < <(yq '.feature_flags[].name' "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

  for flag in "${flag_names[@]}"; do
    default=$(yq ".feature_flags[] | select(.name == $flag) | .default" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")
    description=$(yq ".feature_flags[] | select(.name == $flag) | .description" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

    echo "// ${flag} - ${description}" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

    # make uppercase and strip quotes
    flag=$(echo "${flag}" | tr -d '"')
    flag_upper=$(echo "${flag}" | tr '[:lower:]' '[:upper:]')

    if [[ ${CONFIGURE_FEATURE_FLAGS[$flag]} == true ]]; then
      echo "#define FEATURE_FLAG_${flag_upper} 1" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
    else
      echo "#define FEATURE_FLAG_${flag_upper} 0" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
    fi

    echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  done

  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  echo "// =========================================================================================" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  # C++ code

  echo "#ifdef __cplusplus" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "// Code for feature flags in C++ code" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  # Prepare enum for C++ code
  echo "enum class FeatureFlag {" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  for flag in "${flag_names[@]}"; do
    # make first letter uppercase and replace underscores with big letters
    flag=$(echo "${flag}" | tr -d '"')
    flag_upper=$(echo "${flag}" | sed 's/^\(.\)/\U\1/')
    flag_upper=$(echo "${flag_upper}" | sed 's/_\([a-z]\)/\U\1/g')

    echo "    k${flag_upper}," >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  done
  echo "    kLast," >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "};" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  # Prepare constexpr variable for C++ code
  echo "template <FeatureFlag Flag>" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "constexpr bool FeatureEnabled = false;" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  for flag in "${flag_names[@]}"; do
    default=$(yq ".feature_flags[] | select(.name == $flag) | .default" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")
    description=$(yq ".feature_flags[] | select(.name == $flag) | .description" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

    echo "// ${flag} - ${description}" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

    # make first letter uppercase and replace underscores with big letters
    flag=$(echo "${flag}" | tr -d '"')
    flag_upper=$(echo "${flag}" | sed 's/^\(.\)/\U\1/')
    flag_upper=$(echo "${flag_upper}" | sed 's/_\([a-z]\)/\U\1/g')

    if [[ ${CONFIGURE_FEATURE_FLAGS[$flag]} == true ]]; then
      echo "template <> constexpr bool FeatureEnabled<FeatureFlag::k${flag_upper}> = true;" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
    else
      echo "template <> constexpr bool FeatureEnabled<FeatureFlag::k${flag_upper}> = false;" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
    fi

    echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  done

  # Close the C++ code section
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "#endif // __cplusplus" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"

  # Close the header guard
  echo "" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
  echo "#endif // GENERATED_INCLUDE_AUTOGEN_H_" >> "${CONFIGURE_FEATURE_FLAGS_CXX_PATH}"
}

process_feature_flags() {
  if [[ ! -f "${CONFIGURE_FEATURE_FLAGS_PATH}" ]]; then
    generate_feature_flags_file
  fi

  # Source the feature flags to load existing flags
  source "${CONFIGURE_FEATURE_FLAGS_PATH}"

  if ! grep -q "declare -A CONFIGURE_FEATURE_FLAGS" "${CONFIGURE_FEATURE_FLAGS_PATH}"; then
    dump_error "Feature flags file is not correctly formatted. Delete existing file and re-run the script."
    exit 1
  fi

  local flag_names
  mapfile -t flag_names < <(yq '.feature_flags[].name' "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

  # Add each missing flag to the feature flags file
  for flag in "${flag_names[@]}"; do
    if ! grep -q "CONFIGURE_FEATURE_FLAGS\[${flag}\]=" "${CONFIGURE_FEATURE_FLAGS_PATH}"; then
      default=$(yq ".feature_flags[] | select(.name == $flag) | .default" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")
      description=$(yq ".feature_flags[] | select(.name == $flag) | .description" "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

      echo "# ${flag} - ${description}" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
      echo "CONFIGURE_FEATURE_FLAGS[${flag}]=${default}" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
      echo "" >> "${CONFIGURE_FEATURE_FLAGS_PATH}"
    fi
  done

  # Source the updated feature flags file
  source "${CONFIGURE_FEATURE_FLAGS_PATH}"

  # Verify structure of config file
  for flag in "${!CONFIGURE_FEATURE_FLAGS[@]}"; do
    # Check if flag from file is in definitions
    if ! printf '%s\n' "${flag_names[@]}" | grep -q ${flag}; then
        pretty_warn "Feature flag ${flag} is unrecognized. Please check your feature flags definitions."
    fi
  done

  # Generate CXX feature flag files
  generate_cxx_feature_flag_files
}

generate_cmake_feature_flags() {
  # Source the feature flags to load existing flags
  source "${CONFIGURE_FEATURE_FLAGS_PATH}"

  local conf_cmake="${CONFIGURE_DIR}/../config/conf.generated.cmake"

  local flag_names
  mapfile -t flag_names < <(yq '.feature_flags[].name' "${CONFIGURE_FEATURE_FLAGS_DEFS_PATH}")

  echo "" >> "$conf_cmake"
  echo "# FEATURE FLAGS: " >> "$conf_cmake"
  for flag in "${flag_names[@]}"; do
    # make first letter uppercase and replace underscores with big letters
    flag=$(echo "${flag}" | tr -d '"')
    flag_upper=$(echo "${flag}" | sed 's/^\(.\)/\U\1/')
    flag_upper=$(echo "${flag_upper}" | sed 's/_\([a-z]\)/\U\1/g')

    if [[ ${CONFIGURE_FEATURE_FLAGS[$flag]} == true ]]; then
      echo "set(CMAKE_FEATURE_FLAG_${flag_upper} ON)" >> "${conf_cmake}"
    else
      echo "set(CMAKE_FEATURE_FLAG_${flag_upper} OFF)" >> "${conf_cmake}"
    fi
  done
}

run() {
  pretty_info "Configuring AlkOS build..."
  pretty_info "Architecture: $CONFIGURE_ARCH"
  pretty_info "Build type: $CONFIGURE_BUILD_TYPE"
  pretty_info "Build directory: $CONFIGURE_BUILD_DIR"
  pretty_info "Tool binaries directory: $CONFIGURE_TOOL_BINARIES_DIR"
  pretty_info "Verbose mode: $CONFIGURE_VERBOSE"

  pretty_info "Preparing feature flags..."
  process_feature_flags

  pretty_info "Creating cmake configuration files..."
  # prepare conf.generated.cmake
  local conf_cmake="${CONFIGURE_DIR}/../config/conf.generated.cmake"

  echo "# This file is generated by configure script. Do not edit manually." > "$conf_cmake"
  echo "" >> "$conf_cmake"
  echo "message(STATUS \"Configuring AlkOS build...\")" >> "$conf_cmake"
  echo "set(CMAKE_TOOLCHAIN_FILE \"${CONFIGURE_TOOLCHAINS[$CONFIGURE_ARCH]}\")" >> "$conf_cmake"
  echo "set(CMAKE_FLAGS_FILE \"${CONFIGURE_FLAGS[$CONFIGURE_ARCH]}\")" >> "$conf_cmake"
  echo "set(CMAKE_BUILD_TYPE \"${CONFIGURE_CMAKE_BUILD_TYPES[$CONFIGURE_BUILD_TYPE]}\")" >> "$conf_cmake"
  echo "set(TOOL_BINARIES_DIR \"${CONFIGURE_TOOL_BINARIES_DIR}\")" >> "$conf_cmake"
  echo "set(CMAKE_BUILD_DIR \"${CONFIGURE_BUILD_DIR}\")" >> "$conf_cmake"

  generate_cmake_feature_flags

  pretty_info "Preparing build directory..."
  base_runner "Failed to create build directory" "${CONFIGURE_VERBOSE}" mkdir -p "${CONFIGURE_BUILD_DIR}"

  # let the cmake generate bash.conf and build files
  pretty_info "Running cmake..."
  base_runner "Failed to run cmake" "${CONFIGURE_VERBOSE}" cmake "${CONFIGURE_CMAKE_PATH}" -B "${CONFIGURE_BUILD_DIR}/alkos" \
        -G "Unix Makefiles"
}

main() {
  parse_args "$@"
  process_args
  run
}

main "$@"
