#!/bin/bash

CONFIGURE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
CONFIGURE_SCRIPT_PATH="${CONFIGURE_DIR}/$(basename "$0")"
CONFIGURE_CMAKE_PATH="${CONFIGURE_DIR}/../../CMakeLists.txt"
CONFIGURE_TOOLCHAIN_DIR="${CONFIGURE_DIR}/../../toolchains"

source "${CONFIGURE_DIR}/../utils/pretty_print.bash"
source "${CONFIGURE_DIR}/../utils/helpers.bash"
source "${CONFIGURE_DIR}/../utils/feature_flag_lib.bash"
source "${CONFIGURE_DIR}/../utils/argparse.bash"

declare -A CONFIGURE_TOOLCHAINS=(
  ["x86_64"]="${CONFIGURE_TOOLCHAIN_DIR}/x86_64-toolchain.cmake"
)

declare -A CONFIGURE_FLAGS=(
  ["x86_64"]="${CONFIGURE_TOOLCHAIN_DIR}/x86_64-conf.cmake"
)

declare -A CONFIGURE_BUILD_TYPES_DESC=(
  ["debug"]="Build in debug. Capable of running on real hardware."
  ["release"]="Build in release. Capable of running on real hardware."
)

declare -A CONFIGURE_CMAKE_BUILD_TYPES=(
  ["debug"]="Debug"
  ["release"]="Release"
)

declare -A CONFIGURE_FEATURE_FLAGS_PRESETS=(
  ["test_mode"]="run_test_mode=true debug_spinlock=true debug_output=true debug_traces=true"
  ["regression_mode"]="run_test_mode=false debug_spinlock=true debug_output=true debug_traces=true"
  ["default"]="Refer to feature_flags_schema.yaml..."
)

help_addition() {
    echo "Supported build types:"
    for build in "${!CONFIGURE_BUILD_TYPES_DESC[@]}"; do
      echo "  ${build} - ${CONFIGURE_BUILD_TYPES_DESC[${build}]}"
    done

    echo ""
    echo "Supported feature flag presets:"
    for preset in "${!CONFIGURE_FEATURE_FLAGS_PRESETS[@]}"; do
      echo "  ${preset} - ${CONFIGURE_FEATURE_FLAGS_PRESETS[${preset}]}"
    done
}

parse_args() {
  argparse_init "${CONFIGURE_SCRIPT_PATH}" "Configure AlkOS build" help_addition
  argparse_add_positional "arch" "Target architecture" true "x86_64" "string"
  argparse_add_positional "build" "Build type" true "debug|release" "string"
  argparse_add_option "b|build-dir" "Directory to store build files" false "${CONFIGURE_DIR}/../../build" "" "directory"
  argparse_add_option "t|tool" "Directory to store tool binaries" false "${CONFIGURE_DIR}/../../tools" "" "directory"
  argparse_add_option "v|verbose" "Enable verbose output" false false "" "flag"
  argparse_add_option "p|preset" "Feature flag preset to use" false "" "test_mode|default|regression_mode" "string"
  argparse_parse "$@"
}

configure_script_welcome() {
  pretty_info "Configuring AlkOS build..."
  pretty_info "Architecture: $(argparse_get "arch")"
  pretty_info "Build type: $(argparse_get "build")"
  pretty_info "Build directory: $(argparse_get "b|build-dir")"
  pretty_info "Tool binaries directory: $(argparse_get "t|tool")"
  pretty_info "Verbose mode: $(argparse_get "v|verbose")"
}

configure_script_feature_flags() {
  pretty_info "Preparing feature flags..."

  feature_flags_process

  if [[ -n "$(argparse_get "p|preset")" ]]; then
    if [[ "$(argparse_get "p|preset")" == "default" ]]; then
      pretty_info "Resetting all feature flags to defaults..."
      feature_flags_reset_to_defaults
    else
      pretty_info "Applying feature flag preset: $(argparse_get "p|preset")"
      feature_flags_apply_preset "${CONFIGURE_FEATURE_FLAGS_PRESETS[$(argparse_get "p|preset")]}"
    fi
  fi

  feature_flags_generate_cxx_files
}

configure_script_cmake_config() {
  pretty_info "Creating cmake configuration files..."
  # prepare conf.generated.cmake
  local conf_cmake="${CONFIGURE_DIR}/../../config/conf.generated.cmake"

  echo "# This file is generated by configure script. Do not edit manually." > "$conf_cmake"
  echo "" >> "$conf_cmake"
  echo "message(STATUS \"Configuring AlkOS build...\")" >> "$conf_cmake"
  echo "set(CMAKE_TOOLCHAIN_FILE \"${CONFIGURE_TOOLCHAINS[$(argparse_get "arch")]}\")" >> "$conf_cmake"
  echo "set(CMAKE_FLAGS_FILE \"${CONFIGURE_FLAGS[$(argparse_get "arch")]}\")" >> "$conf_cmake"
  echo "set(CMAKE_BUILD_TYPE \"${CONFIGURE_CMAKE_BUILD_TYPES[$(argparse_get "build")]}\")" >> "$conf_cmake"
  echo "set(TOOL_BINARIES_DIR \"$(argparse_get "t|tool")\")" >> "$conf_cmake"
  echo "set(CMAKE_BUILD_DIR \"$(argparse_get "b|build-dir")\")" >> "$conf_cmake"

  feature_flags_generate_cmake
}

run() {
  configure_script_welcome
  configure_script_feature_flags
  configure_script_cmake_config

  pretty_info "Preparing build directory..."
  base_runner "Failed to create build directory" "$(argparse_get "v|verbose")" mkdir -p "$(argparse_get "b|build-dir")"

  # let the cmake generate bash.conf and build files
  pretty_info "Running cmake..."
  base_runner "Failed to run cmake" "$(argparse_get "v|verbose")" cmake "${CONFIGURE_CMAKE_PATH}" -B "$(argparse_get "b|build-dir")/alkos" \
        -G "Unix Makefiles"
}

main() {
  parse_args "$@"
  run
}

main "$@"
