#ifndef ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_IMPL_DEBUG_HPP_
#define ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_IMPL_DEBUG_HPP_

namespace arch
{
void DebugStack();
}

#endif  // ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_IMPL_DEBUG_HPP_
