//
// Created by Jlisowskyy on 19/10/25.
//

#ifndef ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_INTERRUPT_PARAMS_HPP_
#define ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_INTERRUPT_PARAMS_HPP_

#endif  // ALKOS_KERNEL_ARCH_X86_64_SRC_HAL_INTERRUPT_PARAMS_HPP_
