name: Build and Run tests
description: Build the project and run tests

runs:
  using: composite
  steps:
    - name: Build AlkOS
      shell: bash
      run: sudo "$GITHUB_WORKSPACE/scripts/actions/build_alkos.bash" -v

    - name: Run tests
      shell: bash
      run: python "$GITHUB_WORKSPACE/scripts/tests/runner.py"
