#ifndef ALKOS_KERNEL_INCLUDE_HAL_API_KERNEL_ARGUMENTS_HPP_
#define ALKOS_KERNEL_INCLUDE_HAL_API_KERNEL_ARGUMENTS_HPP_

namespace arch
{
struct KernelArguments {
};
}  // namespace arch

#endif  // ALKOS_KERNEL_INCLUDE_HAL_API_KERNEL_ARGUMENTS_HPP_
