#ifndef ALKOS_KERNEL_ARCH_X86_64_BOOT_LIB_MEM_ERROR_HPP_
#define ALKOS_KERNEL_ARCH_X86_64_BOOT_LIB_MEM_ERROR_HPP_

enum class MemError {
    OutOfMemory,
    InvalidArgument,
};

#endif  // ALKOS_KERNEL_ARCH_X86_64_BOOT_LIB_MEM_ERROR_HPP_
