#ifndef ALKOS_KERNEL_INCLUDE_SYNC_KERNEL_SPINLOCK_HPP_
#define ALKOS_KERNEL_INCLUDE_SYNC_KERNEL_SPINLOCK_HPP_

#include <spinlock.hpp>

using Spinlock = arch::Spinlock;

#endif  // ALKOS_KERNEL_INCLUDE_SYNC_KERNEL_SPINLOCK_HPP_
