# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 The AlkOS Authors
# See the AUTHORS file for the full list of contributors.

#
# This module provides a function for working with bash config files
#

#============================================================================
# alkos_init_bash_config
#============================================================================
function(alkos_init_bash_config)
    file(WRITE "${BASH_CONF_FILE}" "#!/bin/bash\n")
    file(APPEND "${BASH_CONF_FILE}" "# Autogenerated config for ${ARCH}\n")
    file(APPEND "${BASH_CONF_FILE}" "# Do not try to edit this by hand!\n")
    file(APPEND "${BASH_CONF_FILE}" "\n")
endfunction()

#===============================================================================
# alkos_add_to_bash_config
#===============================================================================
function(alkos_add_to_bash_config VARIABLE_NAME VARIABLE_VALUE)
    if(NOT EXISTS "${BASH_CONF_FILE}")
        message(FATAL_ERROR "Bash config file ${BASH_CONF_FILE} does not exist. Please call alkos_init_bash_config first.")
    endif()

    # Update existing variable if it exists, otherwise append at the end
    file(READ "${BASH_CONF_FILE}" BASH_CONF_CONTENTS)
    if(BASH_CONF_CONTENTS MATCHES "export ${VARIABLE_NAME}=")
        string(REGEX REPLACE "export ${VARIABLE_NAME}=\"[^\"]*\"" "export ${VARIABLE_NAME}=\"${VARIABLE_VALUE}\"" UPDATED_BASH_CONF_CONTENTS "${BASH_CONF_CONTENTS}")
        file(WRITE "${BASH_CONF_FILE}" "${UPDATED_BASH_CONF_CONTENTS}\n")
    else()
        file(APPEND "${BASH_CONF_FILE}" "export ${VARIABLE_NAME}=\"${VARIABLE_VALUE}\"\n")
    endif()
endfunction()

#===============================================================================
# alkos_bash_config_append_to_list
#===============================================================================
function(alkos_bash_config_append_to_list VARIABLE_NAME VALUES_TO_APPEND)
    if(NOT EXISTS "${BASH_CONF_FILE}")
        message(FATAL_ERROR "Bash config file ${BASH_CONF_FILE} does not exist. Please call alkos_init_bash_config first.")
    endif()

    # This is how you pass list arguments to a bash script from CMake
    string(REPLACE ";" " " VALUES_TO_APPEND "${VALUES_TO_APPEND}")

    # Read the current value of the variable from the bash config
    file(READ "${BASH_CONF_FILE}" BASH_CONF_CONTENTS)
    if(BASH_CONF_CONTENTS MATCHES "export ${VARIABLE_NAME}=\"[^\"]*\"")
        string(REGEX MATCH "export ${VARIABLE_NAME}=\"([^\"]*)\"" "\\1" _ "${BASH_CONF_CONTENTS}")

        # Append the new value to the existing list
        set(CURRENT_VALUE "${CMAKE_MATCH_1}")
        if(CURRENT_VALUE STREQUAL "")
            set(CURRENT_VALUE "${VALUES_TO_APPEND}")
        else()
            set(CURRENT_VALUE "${CURRENT_VALUE} ${VALUES_TO_APPEND}")
        endif()

        # Update the variable in the bash config
        string(REGEX REPLACE "export ${VARIABLE_NAME}=\"[^\"]*\"" "export ${VARIABLE_NAME}=\"${CURRENT_VALUE}\"" UPDATED_BASH_CONF_CONTENTS "${BASH_CONF_CONTENTS}")
        file(WRITE "${BASH_CONF_FILE}" "${UPDATED_BASH_CONF_CONTENTS}\n")
    else()
        # Variable does not exist, create it
        alkos_add_to_bash_config("${VARIABLE_NAME}" "${VALUES_TO_APPEND}")
    endif()
endfunction()
