name: Reusable - Build Environment Image

on:
  workflow_call:
    outputs:
      image_name:
        description: "The full name/tag of the docker image to use."
        value: ${{ jobs.build-image.outputs.image_name }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image_name: ghcr.io/${{ github.repository }}:${{ steps.get_branch.outputs.name }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sanitize branch name for Docker tag
        id: get_branch
        run: |
          # Converts 'feature/my-cool-branch' to 'feature-my-cool-branch'
          echo "name=${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/.dev.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_branch.outputs.name }}
            ghcr.io/${{ github.repository }}:latest
          labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ steps.get_branch.outputs.name }}
          cache-to: type=gha,mode=max
