# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 The AlkOS Authors
# See the AUTHORS file for the full list of contributors.

TEST_COMMAND_SPECIFIER = "[TEST]"

TEST_DISPLAY_STOP_COMMAND_IN = f"{TEST_COMMAND_SPECIFIER} [LISTEND]\n"
TEST_DISPLAY_STOP_COMMAND_OUT = "exit\r\n"

TEST_NAME_SPECIFIER = "[TESTNAME]"

TEST_FAIL_COMMAND = "[TEST] [FAIL]"
TEST_SUCCESS_COMMAND = "[TEST] [SUCCESS]"
